cash = 100000  # 初始资金

[strategy]
name = "MACD"  # 策略名称

[stock]
symbol = ["000063.SZ"]  # 股票代码
adjust = "qfq"  # 复权方式，qfq-前复权 hfq-后复权 bfq-不复权

[date]  # 回测日期
start_year = 2024
start_month = 9
start_day = 1
end_year = 2025
end_month = 9
end_day = 1

[broker]
commission = 0.0006  # 佣金费率万分之6
stamp_duty = 0.0005  # 印花税 万分之5
transfer_fee = 0.00001  # 过户费 十万分之1
percabs = false  # 为True则使用小数，为False则使用百分数

[log]
doprint = true  # 是否打印日志

# [db]
# # 数据库配置（本地MySQL）
# DB_HOST=localhost
# DB_PORT=3306
# DB_USER=root
# DB_PASSWORD=
# DB_NAME=stock_data
