[MACD]
module = "strategy.macd_strategy"
class = "MACDStrategy"
[MACD.params] 
ma_period = 15  # SMA计算周期
macd_fast = 30  # MACD指标的EMA计算周期，下同
macd_slow = 50
macd_signal = 6
atr_period = 5  # ATR的计算周期
zscore_threshold = 1.5
